version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202107-01

    steps:
      - checkout

      # Add your build steps here
      - run:
          name: Install curl
          command: |
            sudo apt update
            sudo apt install curl

      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
 # Build Docker image
      - run:
          name: Build Docker image
          command: |
            docker build -t gamberge:latest .


# Test Docker image
      - run:
          name: Test Docker image
          command: |
            docker run -d -p 8080:8080 gamberge:latest
            sleep 10  # Wait for container to start
            curl -f http://localhost:8080

